### ISSUE TITLE
Replication To-Do-List

### ISSUE THREAD

**Issue by jbrightuniverse** [HighDimensionalEconLab/HMCExamples.jl#161]
### Within `generate_paper_results`:

- [x] **Standardize all output filenames**
- [x] Pseudotrues are hardcoded everywhere. Is this the ideal implementation?
- [x] Write a `README.md`

#### `baseline_tables.py`:
- [x] For the Dynare with particle filter, do we hardcode the number of particles or is there a better way? Also, determine if this is still up-to-date.
- [x] Does Dynare runtime still exclude "model file generation and compilation"?
- [x] Does Julia runtime still exclude "model file generation and compilation"?
- [x] Pull the pre-adapts and post-adapts number of samples, as well as the runtime, from CSV files for Dynare. Currently these are all set to zero as placeholders.
- [x] Double-check the SGU pseudotrues.
- [x] Double-check that the Dynare SGU sumstats variable order matches the Julia SGU variable order. Sometimes this wasn't the case.
- [x] **Ensure this file runs and there are no visual errors in the generated table.**

#### `rbc_baseline_figures.jl`:
- [x] `num_samples` for Dynare in `dynare_comparison` is hardcoded (as 9000). Update this to pull from CSVs.
- [x] **Ensure this file runs and there are no visual errors in the generated figures.**

#### `rbc_frequentist_tables.py`
- [x] Estimation replication amounts and num_samples are currently all hardcoded. Ideally these should be pulled from JSON in the same manner as `baseline_tables.py`.
- [x] The number of dropped frequentist runs due to errors is no longer 57. These were also hardcoded. These numbers need to be updated with the relevant counts, achievable (and can be generalized) using the `scan_for_errors.py` in `additional_examples`.
- [x] 2nd order joint used to only have 50 experiments. The current data has 100. Ensure that this is not an issue and, if acceptable, is reflected in any text which depends on the number of experiments.
- [x] **Ensure this file runs and there are no visual errors in the generated table.**

#### `rbc_robustness_figures_dynare.jl`
- [x] The Dynare robustness data has a typo in the foldernames: `robusteness` instead of `robustness`. This should be corrected.
- [x] There is no JSON file with the runtime for Dynare. Correct this to pull from the relevant CSV.
- [x] **Ensure this file runs and there are no visual errors in the generated figures.**

#### `rbc_robustness_figures_julia.jl`
- [x] **Ensure this file runs and there are no visual errors in the generated figures.**

#### `rbc_sv_baseline_figures.jl`
- [x] **Ensure this file runs and there are no visual errors in the generated figures.**

#### `sgu_baseline_figures.jl`
- [x] Check why the layout for the epsilons is set to 6x1 instead of 3x1.
- [x] Double-check the SGU pseudotrues.
- [x] **Ensure this file runs and there are no visual errors in the generated figures.**

### Within `run_dynare_samplers`:
- [x] Check that `convert_dynare_output.jl` actually works.
- [x] Ensure that chains are being saved for all Dynare robustness runs.

### Within `run_samplers`:
- [x] Check that `convert_frequentist_output.jl` actually works.
- [x] Rename drop57 to something more generic.
- [x] Adjust `num_simulations` for 2nd order joint if deemed that only 50 runs should be used instead of all 100 that were executed.
